OLMIS-7223: Added fix to approve bug with not passing tests
OpenLMIS/openlmis-requisition pull request #67
Opened 2023-04-13 12:04 UTC by dariapionk

2023-04-21 09:24 UTC, kmadej requested changes

2023-04-21 10:42 UTC, dariapionk commented on src/main/java/org/openlmis/requisition/service/referencedata/UserRoleAssignmentsReferenceDataService.java
> +    List<UUID> facilitySupervisoryNodesIds = requisitionGroupReferenceDataService
I checked on production databases:
- Angola: 58
- Malawi: 135
- Selv: 342

2023-04-25 09:11 UTC, kmadej approved these changes
looks good to me

2023-04-26 09:50 UTC, kmadej commented
looks good to me

2023-04-26 09:50 UTC, merged