OLMIS-7793: Changed AMC calculation for SM facilities
OpenLMIS/openlmis-requisition pull request #93
Opened 2024-03-13 10:29 UTC by anawrotsoldevelo

Jira link: https://openlmis.atlassian.net/browse/OLMIS-7793

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/93)

2024-03-13 17:08 UTC, pwargulak requested changes
I'll continue looking into the PR

2024-03-14 12:31 UTC, nawrotadam commented on src/main/java/org/openlmis/requisition/web/RequisitionV2Controller.java
> +    if (requisitionToUpdate.getTemplate().isPopulateStockOnHandFromStockCards()) {
I like your proposed approach with passing requisitionService to updateFrom. I will attempt to cleanup the code accordingly.

2024-03-26 15:49 UTC, pwargulak approved these changes
Left some questions

2024-03-26 15:49 UTC, pwargulak commented on src/main/java/org/openlmis/requisition/domain/requisition/Requisition.java
> +    if (template.isColumnInTemplateAndDisplayed(ADJUSTED_CONSUMPTION)) {
This is more like FYI, question, not necessary a request to change.

This looks strange, `calculateAndSetStockBasedAverageConsumption` checks for `AVERAGE_CONSUMPTION` column too. If both columns are  displayed, it runs `getNonSkippedFullSupplyRequisitionLineItems` twice. 
Inside the 1st `if`, the value is calculated by some helper method and set inside RequisitionLineItem, but the 2nd `if` uses `RequisitionLineItem.calculateAndSetStockBasedAverageConsumption` method to calculate (so RequisitionLineItem sets its fields by itself) - this gives impression that `RequisitionLineItem` is a full OOP Object with methods and simple value-object at the same time, which is bad design IMO.

I was thinking about this suggestion, but it dosn't solve all concerns:
```
if(template.isColumnInTemplateAndDisplayed(ADJUSTED_CONSUMPTION) || template.isColumnInTemplateAndDisplayed(AVERAGE_CONSUMPTION))  {
  for(RequisitionLineItem line : getNonSkippedFullSupplyRequisitionLineItems(orderables)) {
    if(template.isColumnInTemplateAndDisplayed(ADJUSTED_CONSUMPTION)) {
      line.setAdjustedConsumption(...);
    }

    if(template.isColumnInTemplateAndDisplayed(AVERAGE_CONSUMPTION)) {
      StockCardRangeSummaryDto summaryToAverage = findStockCardRangeSummary(
            stockCardRangeSummariesToAverage, line.getOrderable().getId());

        line.calculateAndSetStockBasedAverageConsumption(summaryToAverage,
            template, periods, previousRequisitions);
    }
  }
}
```

2024-03-28 17:14 UTC, merged